module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    FACULTY: 'FACULTY',
    STUDENT: 'STUDENT',
  },
  ATTENDANCE_STATUS: {
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
    LATE: 'LATE',
    EXCUSED: 'EXCUSED',
  },
  DEFAULT_MIN_ATTENDANCE_PERCENT: 75,
  DEFAULT_WARNING_ATTENDANCE_PERCENT: 65,
};
